.env
backend/connectors/mysqlDB.js
docker-compose.yml
frontend/Dockerfile
prisma.yml

```
docker-compose up
```
Note that `prisma.yml` and `.env` must match.  Hopefully `prisma.yml` can be changed to reference environment variables defined in `.env`.

Working docker-compose config

---

backend/connectors/mysqlDB.js
backend/resolvers/mysqlDBResolver.js
backend/schema/schema.js

Hoping to merge updateAffix from /backend

added a mutation updateAffix, which works in mysql, but not in Altair.

---

.env
backend/connectors/mysqlDB.js
backend/resolvers/mysqlDBResolver.js
backend/schema/schema.js

Copied updateAffix_C, _R, _M and created updateStem and updateRoot.

created mutations for root and stem similar to the updateAffix mutation

---

frontend/src/affixes/AffixList.js
frontend/src/queries/queries.js

Modified AffixList and queries

modified getAffixesQuery to include affixes_Q

---

.env
frontend/src/Colrc.js

Tokens now work for validation of user sign on and roles.. watch out how you import ApolloClient from the libray and needed to change "authorization" keyword to "token" because that is the value we are looking for.

Tokens now work for validation of user sign on and roles

---

.env
backend/connectors/mysqlDB.js
frontend/src/Colrc.js
frontend/src/affixes/AddAffix.js
frontend/src/users/Register.js

login and registration page includes prettified form, appears to work correctly.  Just no push history added yet.

Prettylogin

---

frontend/src/Colrc.js
frontend/src/stylesheets/Colrc.css
frontend/src/users/Register.js

Now user icon and tooltip change upon logging in with a token in local storage.

allowed log in state to be changed upon adding token to local storage

---

.env
frontend/src/Colrc.js
frontend/src/affixes/AddAffix.js
frontend/src/stylesheets/Colrc.css
frontend/src/users/Register.js
frontend/src/users/Users.js

Added password confirmation and masking on registration/login page.  Changed logic to push a newly registered user to the login page on successful registration.

Prettyforms

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/affixes/AddAffix.js

pretty form for add affixes now allows an editnote

revised add affixes form to include editnote

---

frontend/public/index.html
frontend/src/affixes/AddAffix.js
frontend/src/affixes/EditAffix.js
frontend/src/roots/AddRoot.js
frontend/src/users/UserProfile.js

Allowed for validation in the addAffix and editAffix forms in the frontend and the display of GraphQL errors. However, addRoot still has a problem showing GraphQL errors when user token is missing.

AddAffix, EditAffix, AddRoot

---

frontend/src/Colrc.js
frontend/src/roots/RootsDictionary.js
frontend/src/spelling/SpellingPronunciationList.js
frontend/src/stems/StemList.js
frontend/src/users/ChangePassword.js
frontend/src/users/Register.js
frontend/src/users/UserProfile.js
frontend/src/users/Users.js

user area includes logout and password change functions

we have logout and change password

---

frontend/src/affixes/AddAffix.js
frontend/src/stems/AddStem.js
frontend/src/stems/EditStem.js

Now the updates are complete for:
AddAffix    ✔
EditAffix    ✔
AddRoot    ✔
EditRoot    ✔
AddStem    ✔
EditStem    ✔
Yesterday and today, I have been updating these forms to comply with the format that uses Yup, Formik, refetch queries/history push, graphql error messages, and additional edit note field. This was the last one.

Finished updating all of the language tables' Add and Edit forms

---

.env
backend/connectors/mysqlDB.js
backend/resolvers/mysqlDBResolver.js
backend/schema/schema.js
frontend/src/Colrc.js
frontend/src/users/Admin.js
frontend/src/users/Register.js
frontend/src/users/UserProfile.js

Users query built on the backend, getUsersQuery implemented on the front end and new page and route 'admin' pulls users into a table.

Userfeatures

---

backend/package.json
frontend/src/MainMenu.js
frontend/src/NavBar.js
frontend/src/stems/Stems.js
frontend/src/utilities/GetUser.js

getUser can be imported anywhere and you'll have a message that says 'you are logged in as {username} with {roles}'

added a getUser component to the frontend

---

backend/connectors/mysqlDB.js
backend/resolvers/mysqlDBResolver.js
backend/schema/schema.js
frontend/src/queries/queries.js

created mutations add, update, and delete bibliography. Next steps: I still have to test the mutations in Altair with admin and non-admin tokens, and then test the same in the frontend forms.

Bibliography Mutations

---

backend/schema/schema.js
frontend/src/affixes/AddAffix.js
frontend/src/affixes/AffixList.js
frontend/src/bibliography/AddBib.js
frontend/src/bibliography/Bibliography.js

updated AddBib to resemble the validation and errors from addAffix, and found out withApollo isn't necessary in the language data tables' ability to add, delete, and sort.
I also corrected a lacking addbibliography resolver import in schema.

Add Bibliography

---

backend/schema/schema.js
frontend/src/queries/queries.js
frontend/src/spelling/SpellingPronunciationCharts.js

vowel chart now sorts correctly, spelling/charts

---

frontend/src/affixes/EditAffix.js
frontend/src/bibliography/AddBib.js
frontend/src/bibliography/EditBib.js

Edit bibliography form now matches the modern way of using formik and yup, using editAffix as a guide.

Edit Bibliography Form

---

backend/connectors/mysqlDB.js
backend/resolvers/mysqlDBResolver.js
backend/schema/schema.js
frontend/src/Colrc.js
frontend/src/audio/AudioList.js
frontend/src/queries/queries.js

…find-all queries for audiofiles, audiosets, elicitations, texts, textfiles, and textimages.  Disconnected audio page from frontend because audioplayer utility doesn't compile

backend: find-one and find-all queries for texts, audio, elicitations areas 

---

.env
frontend/src/affixes/AddAffix.js
frontend/src/affixes/EditAffix.js
frontend/src/bibliography/AddBib.js
frontend/src/bibliography/EditBib.js
frontend/src/roots/AddRoot.js

Added a segment around the submit button of Add & Edit forms to preserve its position if form labels are added to the input fields above it.

Bibliography, Affixes, Stems, Roots Forms

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/roots/EditRoot.js
frontend/src/roots/RootsDictionary.js
frontend/src/stems/AddStem.js
frontend/src/stems/EditStem.js
frontend/src/stems/StemList.js
frontend/src/stylesheets/Colrc.css
frontend/src/users/ChangePassword.js

"Spellings table now includes active, prevId, userId. Consonants table no longer includes column for Type. I also updated colrc-v2/backend with these changes."

Backend Column Updates

---

.env
frontend/src/stems/StemList.js
frontend/src/stems/Stems.js

added a role check to StemList.js that getsUserfromToken and checks t…o see if the user roles include admin.  If so, then it sets a state variable called admin to true

check Admin role in StemList.js

---

frontend/src/Colrc.js
frontend/src/affixes/AffixList.js
frontend/src/roots/RootsDictionary.js
frontend/src/stems/StemList.js

The admin-only check boxes and "Add Stem" button only appear when the user is logged in as admin. Otherwise, the view-only check boxes appear.

Admin-only view in Stem List

---

.env
backend/config/config.js
backend/tests/app.test.js
frontend/src/Colrc.js

Moved the static server into the new repository so that the files can be served up. We will want to change the .gitignore file at some point to not upload the /public directory.

Static server

---

.env
backend/tests/app.test.js

Added static path to tests, fixed other minor test problems

Added static path to tests, fixed other minor test problems

---

backend/tests/app.test.js

Updated user tests, removed dummy, added view

Updated user tests, removed dummy, added view

---

backend/connectors/mysqlDB.js

Which accompanies the same modification made in the sequelize-testing repo.

created a unique email constraint in connectors

---

frontend/src/Colrc.js
frontend/src/search/Search.js
frontend/src/stems/StemList.js
frontend/src/utilities/DecoratedTextSpan.js
frontend/src/utilities/Helpers.js

navbar rightItems include only user and search.  Text decoration now supports superscript <sup></sup> tags in data.

rightitems pruned, superscript text decoration added 

---

frontend/src/bibliography/Bibliography.js
frontend/src/texts/TextsList.js

Improved bibliography page to show admin-level checkboxes and columns only when logged in as admin/update/owner. Also aligned some indentation in TextsLists.

Bib active=Y

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/affixes/AffixList.js
frontend/src/elicitations/Elicitations.js
frontend/src/queries/queries.js
frontend/src/stems/StemList.js
frontend/src/utilities/AudioPlayer.js

now includes redesigned elicitations page.

dropdown columns on affixes and stems spell out values

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/search/Search.js

backend query for roots table works; schema, connectors and resolvers are updated; we still should test mutations before frontend development

backend queries for new roots table work

---

.env
frontend/src/Colrc.js
frontend/src/queries/queries.js
frontend/src/roots/Roots.js
frontend/src/roots/RootsDictionary.js

add columns and checkboxes for new expanded table

Updated Roots table

---

.env
frontend/src/Colrc.js
frontend/src/affixes/AffixList.js
frontend/src/audio/Audio.js
frontend/src/audio/AudioList.js
frontend/src/bibliography/Bibliography.js
frontend/src/roots/RootsDictionary.js

note new model for setState functions:
`  async handleEditChange(value) {
let currentState = Object.assign({}, this.state) 
currentState.selected.edit = !currentState.selected.edit
await this.setState(currentState)
await this.props.changeAffixState(currentState)
}`

set state for affixes sorting works

---

frontend/src/Colrc.js
frontend/src/roots/RootsDictionary.js

all tested and working as in affixes

updated checkbox and table setstate functions

---

frontend/src/Colrc.js
frontend/src/affixes/AffixList.js
frontend/src/bibliography/Bibliography.js
frontend/src/texts/Texts.js
frontend/src/texts/TextsList.js

state is saved to currentState, and componentWillUnmount is called with a function to send currentState to Colrc.js

Affixes - state works

---

frontend/package.json
frontend/src/affixes/AffixList.js
frontend/src/spelling/SpellingPronunciationCharts.js

Orthographies are displayed as 'Reichard', 'Nicodemus' and 'Salish' rather than R, N, S.

fixed dropdowns in spelling area

---

frontend/src/Colrc.js
frontend/src/affixes/AffixList.js
frontend/src/affixes/Affixes.js
frontend/src/bibliography/Bibliography.js
frontend/src/roots/Roots.js
frontend/src/roots/RootsDictionary.js
frontend/src/spelling/SpellingPronunciation.js
frontend/src/stems/StemList.js
frontend/src/stems/Stems.js

Allowed for Roots and Stems table to check for logged in admin roles using the new way, similar to affixes, referring back to colrc.js for the getUserToken function and state definitions.

Roots and Stems tables updated to behave like Affixes

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/Colrc.js
frontend/src/queries/queries.js
frontend/src/roots/AddRoot.js
frontend/src/roots/Roots.js
frontend/src/roots/RootsDictionary.js
frontend/src/stems/StemList.js
frontend/src/texts/TextsList.js

The texts area of the site displays all the views of all the texts and subordinate elements (I think).  Spot checking would be a good idea.

textlist.js shows all textfiles with numbers per original

---

frontend/src/Colrc.js
frontend/src/roots/RootsDictionary.js
frontend/src/texts/TextsList.js

root symbol added and root-number combined, jwt expiry handled by removing token if expired.  We will need to fix the filter for 'root' so that it can filter on root and number, though.

jwt token expiry, cosmetic changes to roots table columns

---

frontend/src/NavBar.js
frontend/src/accordions/AffixesAccordion.js
frontend/src/accordions/AudioAccordion.js
frontend/src/accordions/BibliographyAccordion.js
frontend/src/accordions/HomeAccordion.js
frontend/src/accordions/RootsAccordion.js
frontend/src/accordions/SpellingAccordion.js
frontend/src/accordions/StemsAccordion.js
frontend/src/accordions/TextsAccordion.js
frontend/src/affixes/AffixMetadata.js
frontend/src/audio/AudioMetadata.js
frontend/src/bibliography/Bibliography.js
frontend/src/home/History.js
frontend/src/roots/RootsHistory.js
frontend/src/roots/RootsMetadata.js
frontend/src/stems/Stems.js
frontend/src/stems/StemsMetadata.js
frontend/src/stylesheets/AccordionTables.css
frontend/src/stylesheets/Colrc.css

filled in missing material for accordions, histories and metadata for roots, stems, affixes, and audio.

accordions, histories, metadata for roots, stems, affixes, audio

---

backend/connectors/mysqlDB.js
backend/schema/schema.js
frontend/src/accordions/ElicitationsAccordion.js
frontend/src/elicitations/Elicitations.js
frontend/src/queries/queries.js
frontend/src/roots/RootColumns.js
frontend/src/roots/RootsDictionary.js
frontend/src/search/Search.js
frontend/src/spelling/SpellingPronunciationCharts.js

various cleanups to elicitations, audio and search - roots page now gets searchtext from search page

elicitations, audio, search

---

frontend/src/App.js

Removed the stray comment bracket from the App.js file, which resolves issue #127.
Nothing else was edited, so should be clear for a merge!

Removed stray comment bracket

---

.gitignore
frontend/src/pages/Affixes.js
frontend/src/pages/LogTable.js
frontend/src/pages/Stems.js
frontend/src/utils/reshapers.js

There was an issue where redirection to log-in page does not happen in affixes and stems menu when there is no JWT token error. This PR solved the issue by revising the code for handling errors and redirecting to log-in page.

1) revised the code to redirect to log-in page when there is no JWT token

---

frontend/src/pages/OdinsonSearch.js

**Revised OdinsonSearch.js to enable searching & displaying on the frontend page**
- Enabled searching for the pattern from the frontend
- Search results (documentId & words) are displayed on the frontend page

Enabled searching & diplaying the result on the frontend

---

frontend/src/App.js
frontend/src/pages/OdinsonSearch.js
frontend/src/pages/OdinsonTable.js
frontend/src/pages/SearchResults.js

Revised Search and SearchResult and created OdinsonTable to prettify the search result for odinson.

#182 Prettify the odinson search result

---

frontend/src/pages/OdinsonTable.js

#182 odinson integration - making a table with a complete result
- Retrieving complete result from restAPI
- cacheing the results and reuse them to go back to the previous pages
- Pagination works, but needs to be improved (i.e., page number exceeding the existing page would result in strange result)

#182 odinson integration - making a table with a complete result

---

frontend/src/pages/OdinsonTable.js

- Fixed the pagination issue when you needed multiple cached pages retrieved

Fixed pagination with improved caching

---

file_upload/app.js
file_upload/package-lock.json
file_upload/package.json
frontend/src/App.js
frontend/src/access/permissions.js
frontend/src/components/NavBar.js
frontend/src/pages/BuildMetadata.js
frontend/src/pages/BuildMetadataTypes.js
frontend/src/pages/ManageTypes.js
frontend/src/pages/MetadataLexicon.js
frontend/src/pages/MetadataLexiconTable.js
frontend/src/pages/MetadataTypesTable.js
frontend/src/pages/Upload.js
frontend/src/queries/queries.js
package-lock.json
package.json

**Added mock-up menus and revised file_upload to upload json files for odinson**
1) Added mock-up menus for odinson file upload and metadata managements
2) Revised `app.js` in file_upload to add json file uploading function for odinson
3) Installed node-fetch module (v.2.6.7) (package.json & package-lock.json in file_upload were revised)

Added mock-up menus and revised file_upload to upload json files for odinson

---

auth/connectors/postgresDB.js
auth/resolvers/postgresDBResolver.js
frontend/src/pages/AddUser.js

Added bcrypt to encrypt passwords

bcrypt passwords to store encypted passes

---

frontend/src/App.js

I cleaned up excess comments in App.js, I think this is ready to go to production.

cleaned excess comments from App.js

---

frontend/src/pages/LogSubTable.js
frontend/src/pages/LogTable.js
frontend/src/utils/reshapers.js

Additional Features:
* Updated fields are highlighted in a very ugly yellow.  Feel free to change this.
* Logs are now sorted by newest first for easier upkeep.
Closes #211

Add subtables to the Log view

---

frontend/src/pages/EditUser.js

The EditUser page now doesn't expose a user's password. And, there is a new confirm password field that validates the password. Then, the password is encrypted and stored in the database.

Modified the EditUser page
